### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by thatsmaik** [b-g/mind-the-uuh-arduino#2]
<img width="917" alt="Schaltplan" src="https://user-images.githubusercontent.com/22634579/125507002-233a45cb-7864-49ac-b12a-1f4a21d7f469.png">

![prototype_naked](https://user-images.githubusercontent.com/22634579/125507330-06fb982a-3be7-41da-8886-d01e996632b5.jpeg)

**Comment by b-g** [comment]
<a href="https://www.youtube.com/watch?v=dL7eOMNSxFU">
<img width="1198" alt="youtube-preview" src="https://user-images.githubusercontent.com/480224/125923954-603a0654-5f60-4715-a07b-063f04d0fd37.png">
</a>
